#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install nginx
# insure that ngnix listen from port 80
# by allowing fire wall
ufw allow 'Nginx HTTP'
# sudu su => is to changing to the root to make changes in existing files
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
