#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install nginx
# insure that ngnix listen from port 80
# by allowing fire wall
ufw allow 'Nginx HTTP'
sudu su
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
