#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get update
sudo apt-get install -y nginx
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default1.bak
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    server_name _;

    location / {
        add_header X-Served-By $hostname
        }
} " >> /etc/nginx/sites-available/default
sudo service nginx restart
