#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# username
# user id
# Home directory path for the user
#!/bin/bash
while read -r line
do
username=$(echo "$line" | cut -d ":" -f 1)
id=$(echo "$line" | cut -d ":" -f 3)
dir=$(echo "$line" | cut -d ":" -f 6)
echo "$username:$id:$dir"
done < /etc/passwd
