#!/usr/bin/env bash
# Bash script that displays the visitor IP
# along with the HTTP status code from the Apache log file.
# and sort it according to number of occurrences for each IP
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
